baseURL: https://blog.quent.in/
languageCode: en-US
defaultContentLanguage: en
title: Quentin Rousseau
theme: "hugo-narrow"

enableEmoji: true
enableRobotsTXT: true

mainSections: ["posts"]

permalinks:
  posts: /blog/:year/:month/:day/:slug/

pagination:
  pagerSize: 10
  path: "page"

taxonomies:
  category: categories
  tag: tags

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    style: dracula
    tabWidth: 2

outputs:
  home: ["HTML", "RSS", "JSON", "WebAppManifest"]

outputFormats:
  WebAppManifest:
    mediaType: "application/manifest+json"
    baseName: "site"
    isPlainText: true

module:
  hugoVersion:
    extended: true
    min: 0.146.0
